/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AllEventsTab` | `/AllEventsTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/app` | `/app`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CreateEventTab` | `/CreateEventTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EventDetailsTab` | `/EventDetailsTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/GuestListTab` | `/GuestListTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeTab` | `/HomeTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ManageEventsTab` | `/ManageEventsTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/AuthService` | `/services/AuthService`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AllEventsTab` | `/AllEventsTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/app` | `/app`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CreateEventTab` | `/CreateEventTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/EventDetailsTab` | `/EventDetailsTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/GuestListTab` | `/GuestListTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeTab` | `/HomeTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ManageEventsTab` | `/ManageEventsTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignIn` | `/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services/AuthService` | `/services/AuthService`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AllEventsTab${`?${string}` | `#${string}` | ''}` | `/AllEventsTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/app${`?${string}` | `#${string}` | ''}` | `/app${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CreateEventTab${`?${string}` | `#${string}` | ''}` | `/CreateEventTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/EventDetailsTab${`?${string}` | `#${string}` | ''}` | `/EventDetailsTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/GuestListTab${`?${string}` | `#${string}` | ''}` | `/GuestListTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeTab${`?${string}` | `#${string}` | ''}` | `/HomeTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ManageEventsTab${`?${string}` | `#${string}` | ''}` | `/ManageEventsTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignIn${`?${string}` | `#${string}` | ''}` | `/SignIn${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services/AuthService${`?${string}` | `#${string}` | ''}` | `/services/AuthService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AllEventsTab` | `/AllEventsTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/app` | `/app`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CreateEventTab` | `/CreateEventTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EventDetailsTab` | `/EventDetailsTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/GuestListTab` | `/GuestListTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeTab` | `/HomeTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ManageEventsTab` | `/ManageEventsTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services/AuthService` | `/services/AuthService`; params?: Router.UnknownInputParams; };
    }
  }
}
